# Common credentials - ENCRYPT THIS FILE WITH ANSIBLE VAULT
# ansible-vault encrypt playbooks/group_vars/all.yml

# Default network device credentials
ansible_user: arun.elango
ansible_password: "-qY42Q_52sOu"

# FortiGate SSH credentials
fortigate_host: "192.168.1.99"
fortigate_user: "admin"
fortigate_password: "changeme"
