---
all:
  children:
    nxos:
      hosts:
        # No hosts currently
    ios:
      hosts:
        test-ngt-frsw-001:
        test-ngt-frsw-002:
    vswitch:
      hosts:
        sandbox:
    cumulus:
      hosts:
        test-edge-01:
        test-edge-02:
    local:
      hosts:
        localhost:
          ansible_connection: local
            # The following hosts are included in localhost.
            # Since, these devices do not have dedicated connection via ansible, they are executed via a python script
            # test_fire001_jpc1

