ansible_connection: ansible.netcommon.network_cli
ansible_network_os: ios
ansible_user: username
ansible_password: password
ansible_ssh_common_args: '-oKexAlgorithms=+diffie-hellman-group1-sha1 -oHostKeyAlgorithms=+ssh-rsa'
ansible_become: yes
ansible_become_method: enable
ansible_become_password: password